require 'yaml'

confDir = File.dirname(__FILE__)
simfaseDevEnvYamlPath = confDir + "/SimfaseDevEnv.yaml"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(confDir + '/scripts/simfase-dev-env.rb')

Vagrant.configure(2) do |config|
    if File.exists? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "~/.bash_aliases"
    end

    if File.exists? simfaseDevEnvYamlPath then
        SimfaseDevEnv.configure(config, YAML::load(File.read(simfaseDevEnvYamlPath)))
    end

    if File.exists? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath
    end
end